namespace TreeGuardians.Editor
{
    /// Seed strings for the LocalizationTable asset: { key, English, Turkish }.
    public static class LocalizationSeed
    {
        public static readonly string[] LoadingTips =
        {
            "tip_bark", "tip_branch", "tip_core", "tip_special", "tip_tools", "tip_upgrade"
        };

        public static readonly string[][] Entries =
        {
            // Boot / loading
            new[] { "boot_ready", "Ready", "Hazır" },
            new[] { "loading_title", "Loading", "Yükleniyor" },
            new[] { "tip_bark", "Break bark plates to expose the targets behind them.", "Arkasındaki hedefleri açmak için kabuk plakalarını kır." },
            new[] { "tip_branch", "A broken branch drops the guardian standing on it.", "Kırılan bir dal üzerindeki muhafızı düşürür." },
            new[] { "tip_core", "The Heartwood only takes full damage once its bark is gone.", "Kalp Özü ancak önündeki kabuk kırılınca tam hasar alır." },
            new[] { "tip_special", "Special energy fills over time and with every hit.", "Özel enerji zamanla ve her isabetle dolar." },
            new[] { "tip_tools", "Tools have long cooldowns; save them for exposed targets.", "Araçların bekleme süresi uzundur; açık hedeflere sakla." },
            new[] { "tip_upgrade", "Duplicate cards become shards for upgrades.", "Tekrar çıkan kartlar yükseltme parçasına dönüşür." },

            // Main menu
            new[] { "menu_battle", "Battle", "Savaş" },
            new[] { "menu_guardians", "Guardians", "Muhafızlar" },
            new[] { "menu_tree", "Tree", "Ağaç" },
            new[] { "menu_tools", "Tools", "Araçlar" },
            new[] { "menu_shop", "Shop", "Mağaza" },
            new[] { "menu_season", "Season", "Sezon" },
            new[] { "menu_events", "Events", "Etkinlikler" },
            new[] { "menu_inbox", "Inbox", "Gelen Kutusu" },
            new[] { "menu_profile", "Profile", "Profil" },
            new[] { "menu_rank", "Rank", "Sıralama" },
            new[] { "menu_quests", "Quests", "Görevler" },
            new[] { "menu_settings", "Settings", "Ayarlar" },
            new[] { "menu_edit_loadout", "Edit Loadout", "Kadroyu Düzenle" },
            new[] { "menu_tree_power", "Tree Power", "Ağaç Gücü" },
            new[] { "menu_arena", "Arena", "Arena" },
            new[] { "menu_next_arena", "Next arena at {0} trophies", "Sonraki arena {0} kupada" },
            new[] { "menu_max_arena", "Highest arena reached", "En yüksek arenaya ulaşıldı" },
            new[] { "menu_daily_reward", "Daily Reward", "Günlük Ödül" },
            new[] { "menu_coming_soon", "Coming soon", "Yakında" },
            new[] { "menu_level", "Level {0}", "Seviye {0}" },
            new[] { "menu_sandbox", "Sandbox", "Test Sahnesi" },

            // Currencies
            new[] { "currency_coins", "Coins", "Altın" },
            new[] { "currency_sap", "Sap", "Öz" },
            new[] { "currency_gems", "Gems", "Mücevher" },
            new[] { "currency_trophies", "Trophies", "Kupa" },
            new[] { "currency_info_coins", "Coins come from battles, chests and quests. Spend them on guardian upgrades.", "Altın savaşlardan, sandıklardan ve görevlerden gelir. Muhafız yükseltmelerinde harcanır." },
            new[] { "currency_info_sap", "Sap comes from battles and chests. Spend it on tree and tool upgrades.", "Öz savaşlardan ve sandıklardan gelir. Ağaç ve araç geliştirmelerinde harcanır." },
            new[] { "currency_info_gems", "Gems are rare. Use them to skip chest timers.", "Mücevher nadirdir. Sandık sürelerini atlamak için kullan." },
            new[] { "currency_go_shop", "Go to Shop", "Mağazaya Git" },

            // Common UI
            new[] { "ui_ok", "OK", "Tamam" },
            new[] { "ui_cancel", "Cancel", "İptal" },
            new[] { "ui_confirm", "Confirm", "Onayla" },
            new[] { "ui_close", "Close", "Kapat" },
            new[] { "ui_back", "Back", "Geri" },
            new[] { "ui_continue", "Continue", "Devam" },
            new[] { "ui_retry", "Retry", "Tekrar" },
            new[] { "ui_home", "Home", "Ana Menü" },
            new[] { "ui_collect", "Collect", "Topla" },
            new[] { "ui_collect_all", "Collect All", "Hepsini Topla" },
            new[] { "ui_claim", "Claim", "Al" },
            new[] { "ui_claimed", "Claimed", "Alındı" },
            new[] { "ui_locked", "Locked", "Kilitli" },
            new[] { "ui_new", "NEW", "YENİ" },
            new[] { "ui_max", "MAX", "MAKS" },
            new[] { "ui_level_short", "Lv.{0}", "Sv.{0}" },
            new[] { "ui_free", "FREE", "ÜCRETSİZ" },
            new[] { "ui_test", "TEST", "TEST" },
            new[] { "ui_yes", "Yes", "Evet" },
            new[] { "ui_no", "No", "Hayır" },
            new[] { "ui_skip", "Skip", "Atla" },
            new[] { "ui_tap_to_continue", "Tap to continue", "Devam etmek için dokun" },
            new[] { "ui_unlock_at", "Unlocks in arena {0}", "{0}. arenada açılır" },
            new[] { "ui_info", "Info", "Bilgi" },
            new[] { "ui_equip", "Equip", "Yerleştir" },
            new[] { "ui_unequip", "Unequip", "Çıkar" },
            new[] { "ui_swap", "Swap", "Değiştir" },
            new[] { "ui_upgrade", "Upgrade", "Yükselt" },
            new[] { "ui_sort", "Sort", "Sırala" },
            new[] { "ui_filter", "Filter", "Filtre" },
            new[] { "ui_all", "All", "Tümü" },
            new[] { "ui_owned", "Owned", "Sahip" },
            new[] { "ui_equipped", "Equipped", "Takılı" },
            new[] { "ui_stats", "Stats", "İstatistik" },

            // Errors / reasons
            new[] { "error_unknown", "Something went wrong.", "Bir şeyler ters gitti." },
            new[] { "insufficient_coins", "Not enough coins", "Yeterli altın yok" },
            new[] { "insufficient_sap", "Not enough sap", "Yeterli öz yok" },
            new[] { "insufficient_gems", "Not enough gems", "Yeterli mücevher yok" },
            new[] { "insufficient_cards", "Not enough cards", "Yeterli kart yok" },
            new[] { "insufficient_title", "Insufficient Resources", "Yetersiz Kaynak" },
            new[] { "insufficient_body", "You need more {0} to do this.", "Bunun için daha fazla {0} gerekiyor." },
            new[] { "guardian_locked", "Guardian is locked", "Muhafız kilitli" },
            new[] { "guardian_max_level", "Maximum level reached", "Maksimum seviyeye ulaşıldı" },
            new[] { "tool_locked", "Tool is locked", "Araç kilitli" },
            new[] { "tool_max_level", "Maximum level reached", "Maksimum seviyeye ulaşıldı" },
            new[] { "tree_max_level", "Maximum level reached", "Maksimum seviyeye ulaşıldı" },
            new[] { "loadout_empty", "Equip at least one guardian to battle.", "Savaşmak için en az bir muhafız yerleştir." },
            new[] { "save_corrupt_title", "Save Problem", "Kayıt Sorunu" },
            new[] { "save_corrupt_body", "Your save file could not be read. A new save was created.", "Kayıt dosyan okunamadı. Yeni bir kayıt oluşturuldu." },
            new[] { "save_recovered_body", "Your save was restored from a backup.", "Kaydın yedekten geri yüklendi." },
            new[] { "reset_save_title", "Reset Progress?", "İlerleme Sıfırlansın mı?" },
            new[] { "reset_save_body", "All progress will be lost. This cannot be undone.", "Tüm ilerleme silinecek. Bu geri alınamaz." },

            // Guardians panel
            new[] { "guardian_upgrade", "Upgrade", "Yükselt" },
            new[] { "guardian_equip", "Equip", "Yerleştir" },
            new[] { "guardian_locked_label", "Locked", "Kilitli" },
            new[] { "guardian_cards", "Cards", "Kartlar" },
            new[] { "guardian_collection", "Collection", "Koleksiyon" },
            new[] { "guardian_equipped_slots", "Equipped", "Kadro" },
            new[] { "guardian_health", "Health", "Can" },
            new[] { "guardian_attack", "Attack", "Saldırı" },
            new[] { "guardian_structure", "Structure Dmg", "Yapı Hasarı" },
            new[] { "guardian_armor", "Armor", "Zırh" },
            new[] { "guardian_crit", "Crit", "Kritik" },
            new[] { "guardian_cooldown", "Cooldown", "Bekleme" },
            new[] { "guardian_range", "Range", "Menzil" },
            new[] { "guardian_special", "Special", "Özel" },
            new[] { "guardian_passive", "Passive", "Pasif" },
            new[] { "guardian_power", "Power", "Güç" },
            new[] { "guardian_unlock_hint", "Collect {0} cards to unlock", "Açmak için {0} kart topla" },
            new[] { "guardian_next_level", "Next level", "Sonraki seviye" },
            new[] { "sort_power", "Power", "Güç" },
            new[] { "sort_level", "Level", "Seviye" },
            new[] { "sort_rarity", "Rarity", "Nadirlik" },
            new[] { "sort_new", "New", "Yeni" },

            // Rarity
            new[] { "rarity_common", "Common", "Sıradan" },
            new[] { "rarity_rare", "Rare", "Nadir" },
            new[] { "rarity_epic", "Epic", "Epik" },
            new[] { "rarity_legendary", "Legendary", "Efsanevi" },

            // Guardian names / descriptions
            new[] { "g_thorn_archer_name", "Chicken", "Tavuk" },
            new[] { "g_thorn_archer_desc", "Balanced ranger with straight thorn shots and a rapid volley.", "Düz diken atışları ve hızlı yaylım ateşiyle dengeli bir korucu." },
            new[] { "g_cone_bomber_name", "Rooster", "Horoz" },
            new[] { "g_cone_bomber_desc", "Lobs heavy cones that splash on impact.", "Çarpınca alan hasarı veren ağır kozalaklar fırlatır." },
            new[] { "g_bark_knight_name", "Turtle", "Kaplumbağa" },
            new[] { "g_bark_knight_desc", "Short range, brutal against structures. Shields itself.", "Kısa menzil, yapılara karşı acımasız. Kendine kalkan açar." },
            new[] { "g_dew_fairy_name", "Duck", "Ördek" },
            new[] { "g_dew_fairy_desc", "Heals allies and fires gently homing dew drops.", "Müttefikleri iyileştirir ve hafif yönlenen çiy damlaları atar." },
            new[] { "g_vine_master_name", "Monkey", "Maymun" },
            new[] { "g_vine_master_desc", "Piercing spears that root enemies and split bark.", "Düşmanı kökleyen ve kabuğu yaran delici mızraklar." },
            new[] { "g_spore_alchemist_name", "Parrot", "Papağan" },
            new[] { "g_spore_alchemist_desc", "Leaves poison clouds that linger.", "Kalıcı zehir bulutları bırakır." },
            new[] { "g_owl_scout_name", "Owl", "Baykuş" },
            new[] { "g_owl_scout_desc", "Fires from above with a high critical chance.", "Yüksekten ateş eder; kritik şansı yüksektir." },
            new[] { "g_oak_warden_name", "Bear", "Ayı" },
            new[] { "g_oak_warden_desc", "A living wall that armors nearby allies.", "Yakındaki müttefiklere zırh veren yaşayan bir duvar." },
            new[] { "g_firefly_mage_name", "Cat", "Kedi" },
            new[] { "g_firefly_mage_desc", "Chains energy between targets.", "Enerjiyi hedefler arasında zincirler." },
            new[] { "g_beaver_engineer_name", "Penguin", "Penguen" },
            new[] { "g_beaver_engineer_desc", "Shortens tool cooldowns for the whole tree.", "Tüm ağacın araç bekleme sürelerini kısaltır." },
            new[] { "g_hedgehog_sniper_name", "Eagle", "Kartal" },
            new[] { "g_hedgehog_sniper_desc", "Unleashes a salvo of quills.", "Bir diken salvosu fırlatır." },
            new[] { "g_ancient_sprout_name", "Wild Boar", "Yaban Domuzu" },
            new[] { "g_ancient_sprout_desc", "Blesses the team and returns once from defeat.", "Takımı kutsar ve bir kez yeniden doğar." },

            // Specials
            new[] { "special_power_shot", "Power Shot", "Güçlü Atış" },
            new[] { "special_salvo", "Salvo", "Salvo" },
            new[] { "special_heal", "Dew Bloom", "Çiy Çiçeği" },
            new[] { "special_root", "Root Grip", "Kök Kıskacı" },
            new[] { "special_poison", "Spore Cloud", "Spor Bulutu" },
            new[] { "special_chain", "Chain Light", "Zincir Işık" },
            new[] { "special_shield", "Bark Wall", "Kabuk Duvarı" },
            new[] { "special_armor", "Oak Blessing", "Meşe Kutsaması" },
            new[] { "special_tool_reset", "Quick Hands", "Hızlı Eller" },
            new[] { "special_team_buff", "Ancient Song", "Kadim Şarkı" },
            new[] { "passive_none", "None", "Yok" },
            new[] { "passive_crit", "+{0}% crit chance", "+%{0} kritik şansı" },
            new[] { "passive_shield_on_hit", "Gains shield on hit", "Vurunca kalkan kazanır" },
            new[] { "passive_heal", "Regenerates health", "Canını yeniler" },
            new[] { "passive_armor_aura", "Armor aura for allies", "Müttefiklere zırh aurası" },
            new[] { "passive_tool_cd", "Tool cooldown -{0}%", "Araç bekleme -%{0}" },
            new[] { "passive_structure", "+{0}% structure damage", "+%{0} yapı hasarı" },
            new[] { "passive_rebirth", "Returns once after defeat", "Yenilince bir kez geri döner" },

            // Tools
            new[] { "t_root_catapult_name", "Root Catapult", "Kök Mancınığı" },
            new[] { "t_root_catapult_desc", "Lobs a heavy boulder that crushes structures.", "Yapıları ezen ağır bir kaya fırlatır." },
            new[] { "t_dew_sprayer_name", "Dew Sprayer", "Çiy Püskürtücü" },
            new[] { "t_dew_sprayer_desc", "Heals a tree section and nearby guardians.", "Bir ağaç bölümünü ve yakın muhafızları iyileştirir." },
            new[] { "t_bee_hive_name", "Bee Hive", "Arı Kovanı" },
            new[] { "t_bee_hive_desc", "Releases a homing swarm of bees.", "Yönlenen bir arı sürüsü salar." },
            new[] { "t_wind_bell_name", "Wind Bell", "Rüzgâr Çanı" },
            new[] { "t_wind_bell_desc", "Deflects incoming projectiles slightly.", "Gelen mermileri hafifçe saptırır." },
            new[] { "t_vine_net_name", "Vine Net", "Sarmaşık Ağı" },
            new[] { "t_vine_net_desc", "Slows and locks a target area.", "Hedef bölgeyi yavaşlatır ve kilitler." },
            new[] { "t_seed_shield_name", "Seed Shield", "Tohum Kalkanı" },
            new[] { "t_seed_shield_desc", "A temporary barrier on a chosen section.", "Seçilen bölümde geçici bariyer." },
            new[] { "tools_equipped", "Equipped Tools", "Takılı Araçlar" },
            new[] { "tools_collection", "All Tools", "Tüm Araçlar" },

            // Tree upgrades
            new[] { "tree_heartwood", "Heartwood Level", "Kalp Özü Seviyesi" },
            new[] { "tree_heartwood_desc", "Increases total core health.", "Toplam ana canı artırır." },
            new[] { "tree_bark", "Bark Thickness", "Kabuk Kalınlığı" },
            new[] { "tree_bark_desc", "Increases armor of all sections.", "Tüm bölümlerin zırhını artırır." },
            new[] { "tree_branch", "Branch Durability", "Dal Dayanıklılığı" },
            new[] { "tree_branch_desc", "Increases branch health.", "Dal canını artırır." },
            new[] { "tree_root", "Root Strength", "Kök Gücü" },
            new[] { "tree_root_desc", "Reduces splash and shake damage.", "Alan ve sarsıntı hasarını azaltır." },
            new[] { "tree_sap", "Sap Flow", "Öz Akışı" },
            new[] { "tree_sap_desc", "Faster special energy in battle.", "Savaşta özel enerji daha hızlı dolar." },
            new[] { "tree_canopy", "Canopy Growth", "Taç Gelişimi" },
            new[] { "tree_canopy_desc", "Unlocks guardian and tool slots.", "Muhafız ve araç yuvaları açar." },
            new[] { "tree_tier_sprouting", "Sprouting", "Filizlenen" },
            new[] { "tree_tier_strong", "Strong", "Güçlü" },
            new[] { "tree_tier_ancient", "Ancient", "Kadim" },
            new[] { "tree_panel_title", "Tree of Life", "Yaşam Ağacı" },

            // Arenas
            new[] { "arena_sunny_grove", "Sunny Grove", "Güneşli Koruluk" },
            new[] { "arena_misty_swamp", "Misty Swamp", "Sisli Bataklık" },
            new[] { "arena_crimson_autumn", "Crimson Autumn", "Kızıl Sonbahar" },
            new[] { "arena_moonlit_forest", "Moonlit Forest", "Ayışığı Ormanı" },
            new[] { "arena_recommended_power", "Recommended power", "Önerilen güç" },
            new[] { "arena_unlock_trophies", "{0} trophies to unlock", "Açmak için {0} kupa" },

            // Battle prep / match loading
            new[] { "prep_title", "Battle Prep", "Savaş Hazırlığı" },
            new[] { "prep_your_loadout", "Your Loadout", "Senin Kadron" },
            new[] { "prep_enemy_loadout", "Enemy Loadout", "Rakip Kadro" },
            new[] { "prep_difficulty", "Difficulty", "Zorluk" },
            new[] { "prep_start", "Start Battle", "Savaşı Başlat" },
            new[] { "difficulty_easy", "Easy", "Kolay" },
            new[] { "difficulty_normal", "Normal", "Normal" },
            new[] { "difficulty_hard", "Hard", "Zor" },
            new[] { "prep_offline_bot", "Offline bot match", "Çevrimdışı bot maçı" },

            // Battle
            new[] { "battle_ready", "READY", "HAZIR" },
            new[] { "battle_fight", "FIGHT!", "SAVAŞ!" },
            new[] { "battle_tree_exposed", "TREE EXPOSED!", "AĞAÇ AÇIĞA ÇIKTI!" },
            new[] { "battle_core_exposed", "HEARTWOOD EXPOSED!", "KALP ÖZÜ AÇIKTA!" },
            new[] { "battle_victory", "VICTORY", "ZAFER" },
            new[] { "battle_defeat", "DEFEAT", "YENİLGİ" },
            new[] { "battle_draw", "DRAW", "BERABERE" },
            new[] { "battle_time_up", "TIME UP", "SÜRE DOLDU" },
            new[] { "battle_branch_broken", "BRANCH DOWN!", "DAL KIRILDI!" },
            new[] { "battle_you", "You", "Sen" },
            new[] { "battle_bot", "Bot", "Bot" },
            new[] { "battle_paused", "Paused", "Duraklatıldı" },
            new[] { "battle_resume", "Resume", "Devam Et" },
            new[] { "battle_forfeit", "Forfeit", "Pes Et" },
            new[] { "battle_forfeit_confirm", "Leave the battle? It counts as a defeat.", "Savaştan ayrılmak istiyor musun? Yenilgi sayılır." },
            new[] { "battle_offline", "OFFLINE BOT", "ÇEVRİMDIŞI BOT" },
            new[] { "battle_special_ready", "Special ready", "Özel hazır" },
            new[] { "battle_stunned", "Stunned", "Sersem" },
            new[] { "battle_your_turn", "YOUR TURN", "SIRA SENDE" },
            new[] { "battle_enemy_turn", "ENEMY TURN", "RAKİBİN SIRASI" },
            new[] { "battle_turn_timeout", "TIME'S UP!", "SÜRE DOLDU!" },
            new[] { "battle_select_guardian", "Pick a guardian card", "Bir muhafız kartı seç" },
            new[] { "battle_tap_to_fire", "Tap the enemy castle to fire (or drag to aim)", "Ateş etmek için rakip kaleye dokun (ya da sürükleyerek nişan al)" },

            // Results
            new[] { "results_title_victory", "Victory!", "Zafer!" },
            new[] { "results_title_defeat", "Defeat", "Yenilgi" },
            new[] { "results_title_draw", "Draw", "Berabere" },
            new[] { "results_damage", "Damage dealt", "Verilen hasar" },
            new[] { "results_core_left", "Heartwood left", "Kalan Kalp Özü" },
            new[] { "results_guardians_alive", "Guardians alive", "Yaşayan muhafız" },
            new[] { "results_accuracy", "Accuracy", "İsabet" },
            new[] { "results_rewards", "Rewards", "Ödüller" },
            new[] { "results_trophies", "Trophies", "Kupa" },
            new[] { "results_unlocked", "Unlocked!", "Açıldı!" },
            new[] { "results_new_arena", "New arena unlocked", "Yeni arena açıldı" },
            new[] { "results_chest_full", "Chest slots full", "Sandık yuvaları dolu" },

            // Chests
            new[] { "chest_open", "Open", "Aç" },
            new[] { "chest_unlocking", "Unlocking", "Açılıyor" },
            new[] { "chest_ready", "Ready!", "Hazır!" },
            new[] { "chest_start", "Start", "Başlat" },
            new[] { "chest_empty_slot", "Empty slot", "Boş yuva" },
            new[] { "chest_skip", "Skip for {0}", "{0} ile atla" },
            new[] { "chest_busy", "Another chest is unlocking", "Başka bir sandık açılıyor" },
            new[] { "chest_twig", "Twig Chest", "Dal Sandığı" },
            new[] { "chest_grove", "Grove Chest", "Koru Sandığı" },
            new[] { "chest_ancient", "Ancient Chest", "Kadim Sandık" },
            new[] { "chest_moon", "Moon Chest", "Ay Sandığı" },
            new[] { "chest_sun", "Sun Chest", "Güneş Sandığı" },
            new[] { "chest_tap_to_open", "Tap to open", "Açmak için dokun" },

            // Quests / achievements / daily
            new[] { "quests_title", "Quests", "Görevler" },
            new[] { "quests_tab_quests", "Quests", "Görevler" },
            new[] { "quests_tab_achievements", "Achievements", "Başarımlar" },
            new[] { "quests_daily", "Daily", "Günlük" },
            new[] { "q_play_1_title", "Play a battle", "Bir savaş oyna" },
            new[] { "q_play_1_desc", "Play 1 battle in any arena.", "Herhangi bir arenada 1 savaş oyna." },
            new[] { "q_win_1_title", "Win a battle", "Bir savaş kazan" },
            new[] { "q_win_1_desc", "Win 1 battle.", "1 savaş kazan." },
            new[] { "q_bark_3_title", "Bark breaker", "Kabuk kıran" },
            new[] { "q_bark_3_desc", "Break 3 bark plates.", "3 kabuk plakası kır." },
            new[] { "q_upgrade_1_title", "Grow stronger", "Güçlen" },
            new[] { "q_upgrade_1_desc", "Upgrade a guardian.", "Bir muhafızı yükselt." },
            new[] { "q_chest_1_title", "Treasure", "Hazine" },
            new[] { "q_chest_1_desc", "Open a chest.", "Bir sandık aç." },
            new[] { "q_special_500_title", "Special force", "Özel güç" },
            new[] { "q_special_500_desc", "Deal 500 damage with special abilities.", "Özel yeteneklerle 500 hasar ver." },
            new[] { "a_first_victory_title", "First Victory", "İlk Zafer" },
            new[] { "a_first_victory_desc", "Win your first battle.", "İlk savaşını kazan." },
            new[] { "a_marksman_title", "Master Marksman", "Usta Nişancı" },
            new[] { "a_marksman_desc", "Deal 5000 special damage.", "5000 özel hasar ver." },
            new[] { "a_branch_breaker_title", "Branch Breaker", "Dal Kıran" },
            new[] { "a_branch_breaker_desc", "Break 10 branches.", "10 dal kır." },
            new[] { "a_collector_title", "Collector", "Koleksiyoncu" },
            new[] { "a_collector_desc", "Upgrade guardians 20 times.", "Muhafızları 20 kez yükselt." },
            new[] { "a_ancient_tree_title", "Ancient Tree", "Kadim Ağaç" },
            new[] { "a_ancient_tree_desc", "Play 50 battles.", "50 savaş oyna." },
            new[] { "daily_title", "Daily Reward", "Günlük Ödül" },
            new[] { "daily_day", "Day {0}", "{0}. Gün" },
            new[] { "daily_next_in", "Next in {0}", "Sonraki: {0}" },

            // Shop (mock)
            new[] { "shop_title", "Shop", "Mağaza" },
            new[] { "shop_free_chest", "Free Daily Chest", "Günlük Ücretsiz Sandık" },
            new[] { "shop_coin_pack", "Coin Pack", "Altın Paketi" },
            new[] { "shop_sap_pack", "Sap Pack", "Öz Paketi" },
            new[] { "shop_starter_pack", "Starter Pack", "Başlangıç Paketi" },
            new[] { "shop_bark_skin", "Bark Skin", "Kabuk Görünümü" },
            new[] { "shop_mock_note", "Purchases are simulated in this prototype.", "Bu prototipte satın almalar simüle edilir." },
            new[] { "shop_watch_ad", "Watch Ad (TEST)", "Reklam İzle (TEST)" },

            // Settings
            new[] { "settings_title", "Settings", "Ayarlar" },
            new[] { "settings_language", "Language", "Dil" },
            new[] { "settings_music", "Music", "Müzik" },
            new[] { "settings_sfx", "Sound Effects", "Ses Efektleri" },
            new[] { "settings_vibration", "Vibration", "Titreşim" },
            new[] { "settings_reduce_haptics", "Reduce Haptics", "Titreşimi Azalt" },
            new[] { "settings_reduce_motion", "Reduce Motion", "Hareketi Azalt" },
            new[] { "settings_quality", "Quality", "Kalite" },
            new[] { "settings_aim_mode", "Aim Mode", "Nişan Modu" },
            new[] { "settings_replay_tutorial", "Replay Tutorial", "Öğreticiyi Tekrarla" },
            new[] { "settings_reset_save", "Reset Progress", "İlerlemeyi Sıfırla" },
            new[] { "settings_version", "Version", "Sürüm" },
            new[] { "quality_low", "Low", "Düşük" },
            new[] { "quality_medium", "Medium", "Orta" },
            new[] { "quality_high", "High", "Yüksek" },
            new[] { "aim_pull_back", "Pull back", "Geri çek" },
            new[] { "aim_direct", "Direct drag", "Doğrudan sürükle" },
            new[] { "language_en", "English", "English" },
            new[] { "language_tr", "Türkçe", "Türkçe" },

            // Profile / rank
            new[] { "profile_title", "Profile", "Profil" },
            new[] { "profile_battles", "Battles", "Savaşlar" },
            new[] { "profile_wins", "Wins", "Galibiyet" },
            new[] { "profile_best_trophies", "Best trophies", "En iyi kupa" },
            new[] { "rank_title", "Arena Path", "Arena Yolu" },
            new[] { "rank_current", "Current", "Mevcut" },

            // Tutorial
            new[] { "tut_step_1", "Tap a guardian card to select it.", "Seçmek için bir muhafız kartına dokun." },
            new[] { "tut_step_2", "Tap the enemy castle to fire (or drag to aim).", "Ateş etmek için rakip kaleye dokun (ya da sürükleyerek nişan al)." },
            new[] { "tut_step_3", "Hit the enemy walls to open holes.", "Delik açmak için rakip duvarlarını vur." },
            new[] { "tut_step_4", "Guardians behind a hole can be hit!", "Delik açılan yerdeki muhafızlar vurulabilir!" },
            new[] { "tut_step_5", "Use a tool from the tool bar.", "Araç çubuğundan bir araç kullan." },
            new[] { "tut_step_6", "Defeat every enemy guardian to win!", "Kazanmak için tüm rakip muhafızları yen!" },
            new[] { "tut_step_7", "Collect your rewards.", "Ödüllerini topla." },
            new[] { "tut_step_8", "Upgrade a guardian with your new cards.", "Yeni kartlarınla bir muhafızı yükselt." },
            new[] { "tut_skip", "Skip tutorial", "Öğreticiyi atla" },

            // Popups
            new[] { "popup_reward_title", "Rewards", "Ödüller" },
            new[] { "popup_unlock_title", "New Guardian!", "Yeni Muhafız!" },
            new[] { "popup_unlock_tool", "New Tool!", "Yeni Araç!" },
            new[] { "popup_connection_title", "Connection", "Bağlantı" },
            new[] { "popup_connection_body", "Online play is not available in this prototype. Battles run against an offline bot.", "Bu prototipte çevrimiçi oyun yok. Savaşlar çevrimdışı bota karşı oynanır." },
            new[] { "popup_confirm_upgrade", "Upgrade {0} to level {1}?", "{0} seviye {1}'e yükseltilsin mi?" },

            // Stats labels
            new[] { "stat_health", "HP", "CAN" },
            new[] { "stat_attack", "ATK", "SAL" },
            new[] { "stat_structure", "STR", "YAPI" },
            new[] { "stat_armor", "ARM", "ZRH" },

            // Debug
            new[] { "debug_title", "Debug", "Hata Ayıklama" },
            new[] { "debug_add_coins", "+1000 Coins", "+1000 Altın" },
            new[] { "debug_add_sap", "+100 Sap", "+100 Öz" },
            new[] { "debug_add_gems", "+50 Gems", "+50 Mücevher" },
            new[] { "debug_reset", "Reset Save", "Kaydı Sıfırla" },
            new[] { "debug_unlock_all", "Unlock All", "Hepsini Aç" },
            new[] { "debug_finish_chests", "Finish Chest Timers", "Sandık Sürelerini Bitir" },
        };
    }
}
